### PR TITLE
Highlighting

### PR DESCRIPTION
**Pull request by david-driscoll**
highlighting

### CODE REVIEW

**Comment by adriaanp** [comment]
Sweet!

**Comment by david-driscoll** [comment]
Now with configuration!

**Comment by nosami** [comment]
This just happened. No idea how :(

**Comment by david-driscoll** [comment]
I've seen that before... sometimes things can slip out of sync.  Changing tabs will force it to rehighlight and so will continuing to type.

**Comment by Mpdreamz** [comment]
I rebased this branch against master and updated its getClientForEditor usage but editing became very very laggy :(

Hopefully its only my local rewrite that introduced this though. (not force pushing because I do not know what pending commits you have).

**Comment by david-driscoll** [comment]
Maybe push it to a separate branch, and I can take a look when I have a moment?

**Comment by david-driscoll** [comment]
Note depends on https://github.com/OmniSharp/omnisharp-roslyn/pull/251

**Comment by nosami** [comment]
I get the following error on startup with this branch

```
TypeError: Cannot read property 'registry' of undefined
  at /Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/highlight.js:355:32
  at Object.<anonymous> (/Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/highlight.js:363:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:5:19)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at /Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:141:29
  at /Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4785:51
  at tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at InnerObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4806:43)
  at InnerObserver.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at InnerObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5151:29)
  at InnerObserver.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at InnerObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:3627:90)
  at InnerObserver.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at InnerObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4810:14)
  at InnerObserver.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5484:17)
  at AsyncSubject.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at AutoDetachObserver.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at handler (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.async.js:373:20)
  at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by david-driscoll** [comment]
What was the action you were trying, go to definition?






Sent from Windows Mail





From: Jason Imison
Sent: ‎Sunday‎, ‎July‎ ‎5‎, ‎2015 ‎1‎:‎00‎ ‎PM
To: OmniSharp/omnisharp-atom
Cc: David Driscoll





I get the following error on startup with this branch
TypeError: Cannot read property 'registry' of undefined
  at /Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/highlight.js:355:32
  at Object.<anonymous> (/Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/highlight.js:363:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:5:19)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at /Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:141:29
  at /Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4785:51
  at tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at InnerObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4806:43)
  at InnerObserver.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at InnerObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5151:29)
  at InnerObserver.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at InnerObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:3627:90)
  at InnerObserver.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at InnerObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4810:14)
  at InnerObserver.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5484:17)
  at AsyncSubject.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at AutoDetachObserver.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at handler (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.async.js:373:20)
  at FSReqWrap.oncomplete (fs.js:77:15)

**Comment by nosami** [comment]
This was just starting atom. I didn't perform any action.

**Comment by nosami** [comment]
I get the same error after the fix.

**Pull request merged**
