### PR TITLE
Roslyn!

### PR DESCRIPTION
**Pull request by ctolkien**
Few major chunks rolled up here:

* Omnisharp-roslyn!
* Icon support in intellisense
* (WIP) refactor to new API, some major changes to the way the icon/statusbar/dock works (now using the status-bar service), ~~4 deprecations still to go~~

### CODE REVIEW

**Comment by ctolkien** [comment]
Oh, should mention, fixes #51

**Comment by ctolkien** [comment]
Also fixes #62

**Comment by Mpdreamz** [comment]
So much awesome in this PR :+1: 

Looking it over right now but have the following ponder did you try running this on OSX/Linux?

Its still trying to run omnisharp bash script with mono on non win32 systems :)

Looking into this now though getting rather nasty:

Uncaught Error: spawn EACCES

errors.

**Comment by ctolkien** [comment]
>did you try running this on OSX/Linux?

Nope, been working on win only at this stage. I'll have access to OSX over the weekend, but will need further help with the *nix side. I might suggest trashing this PR and getting a roslyn branch going so it's easier for others to test/contribute, thoughts?

I've some other changes coming down the pipe too to with regard to re-implementing the way the 'codecheck' actions are performed as there's some issues around that.

**Comment by ctolkien** [comment]
Closing, to PR into a different branch.

**Pull request closed without merging**
