### PR TITLE
Turn off Server and show off

### PR DESCRIPTION
**Pull request by sgwill**
Work in Progress...

#111 brought the klr thread count down to 2, and kills both on Atom Exit. But with #145 Toggle doesn't show that the server has stopped. 

This PR clears the server output and turns off the icon. It does not (yet) actually kill the server.

The question is: do we actually kill the server, or should we instead skip this until we can get #123 working, and instead always leave Omnisharp running?

### CODE REVIEW

**Comment by Mpdreamz** [comment]
In my opinion we should really kill the server and dth.

**Comment by sgwill** [comment]
I agree, actually. I'll add to the PR with that.

**Comment by ctolkien** [comment]
+1 on killing everything.

**Comment by david-driscoll** [comment]
The it looks good locally, but if we're adding stopping of the klr process, I'll leave this alone for now.

**Comment by sgwill** [comment]
Hmm, looks like `/stopserver` isn't implemented yet in omnisharp-roslyn. Someone has a gist over in the Roslyn issue https://github.com/OmniSharp/omnisharp-roslyn/issues/16. I think I'll try pulling that gist and see if it does what we're looking for. That would make the update to omnisharp-atom easier.

**Comment by sgwill** [comment]
I updated this PR with the new node-client bits. A few things.

First, I think the `/stopserver` issue should be moved to `omnisharp-node-client`. Let the node-client worry about properly starting and stopping the server. I'll open an issue, because it doesn't look like it's cleaning up after itself at the moment.

Second, I can toggle on and off, but if I'm on a .cs file, the server automatically re-toggles back on again. I guess that's probably a new issue.

So, in the end, this PR just clears the output pane and turns off the omnisharp icon if the server is (or at least if the server is supposed to be) off.

**Comment by sgwill** [comment]
PR now accomplishes two things:

1. When Omnisharp is toggled off, clear server output and turn off icon, to show that Omnisharp is off.
2. When Omnisharp is automatically turned on, it can now attach to the output. This fixes #204 

I think the thread killing and /stopserver stuff should be handled by the node-client now, so this PR should be complete.

**Comment by nosami** [comment]
I just tested this but I wasn't able to see this working.

There are merge conflict markers in tsconfig.json. Think you might have an issue with your git line endings too - I can't see what changed.

**Comment by ctolkien** [comment]
wtb: .gitattributes

**Comment by nosami** [comment]
Regarding klr processes, it should be the server's responsibility to close the DTH process as the editor has no way of determining the pid.

Here's what's currently happening - 

mono-bug-fixed2

**Comment by sgwill** [comment]
@ctolkien yes, I know.

@nosami I agree.

**Comment by nosami** [comment]
Created an issue over here for terminating DTH https://github.com/OmniSharp/omnisharp-roslyn/issues/212

**Comment by nosami** [comment]
Works well... closing this in favour of #242

**Pull request closed without merging**
