### PR TITLE
Feature - Signature Help

### PR DESCRIPTION
**Pull request by david-driscoll**

### CODE REVIEW

**Comment by Mpdreamz** [comment]
Love love this feature functionally! Estatically this could use a couple of touch ups, will try and post a gif of what I'm seeing later. +1 to merge thought

**Comment by david-driscoll** [comment]
@Mpdreamz got a chance to play with the latest changes, or have another comments?

**Comment by Mpdreamz** [comment]
No not seen the recent updates yet was out abroad on company retreat now on
my way back home.

**Comment by david-driscoll** [comment]
I had to forgot to comment, so my bad :D

**Pull request merged**
