### PR TITLE
Use package-deps

### PR DESCRIPTION
**Pull request by steelbrain**
Fixes https://github.com/OmniSharp/omnisharp-atom/issues/288
We don't need to show a notification here, it handles it himself.

[Review on Reviewable](https://reviewable.io/reviews/omnisharp/omnisharp-atom/497)

### CODE REVIEW

**Comment by david-driscoll** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

<sup>**[lib/omnisharp-atom/omnisharp-atom.ts, line 27 \[r1\]](https://reviewable.io:443/reviews/omnisharp/omnisharp-atom/497#-Jyh84RhVAchh_tpyc6m)** ([raw file](https://github.com/omnisharp/omnisharp-atom/blob/03cd90562c31ad23dbfcd0fa2970cb121e83b8f5/lib/omnisharp-atom/omnisharp-atom.ts#L27)):</sup>
I would assign this promise to a variable.

---

<sup>**[lib/omnisharp-atom/omnisharp-atom.ts, line 56 \[r1\]](https://reviewable.io:443/reviews/omnisharp/omnisharp-atom/497#-Jyh8fi4QCMv2LznrkJH)** ([raw file](https://github.com/omnisharp/omnisharp-atom/blob/03cd90562c31ad23dbfcd0fa2970cb121e83b8f5/lib/omnisharp-atom/omnisharp-atom.ts#L56)):</sup>
Then using the new promise value, replace `started.subscribe(() => {` with `dependenciesInstalled.then(() => started.toPromise()).then(() =>{`

This should delay bootstrap until we're sure all the dependencies are installed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/omnisharp/omnisharp-atom/497)

**Comment by david-driscoll** [comment]
On a side note reviewable is kinda cool... to bad it doesn't inline the comments with the github PR :frowning:

**Comment by steelbrain** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[lib/omnisharp-atom/omnisharp-atom.ts, line 27 \[r1\]](https://reviewable.io:443/reviews/omnisharp/omnisharp-atom/497#-Jyh84RhVAchh_tpyc6m)** ([raw file](https://github.com/omnisharp/omnisharp-atom/blob/03cd90562c31ad23dbfcd0fa2970cb121e83b8f5/lib/omnisharp-atom/omnisharp-atom.ts#L27)):</sup>
Done

---

<sup>**[lib/omnisharp-atom/omnisharp-atom.ts, line 56 \[r1\]](https://reviewable.io:443/reviews/omnisharp/omnisharp-atom/497#-Jyh8fi4QCMv2LznrkJH)** ([raw file](https://github.com/omnisharp/omnisharp-atom/blob/03cd90562c31ad23dbfcd0fa2970cb121e83b8f5/lib/omnisharp-atom/omnisharp-atom.ts#L56)):</sup>
Done

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/omnisharp/omnisharp-atom/497)

**Comment by david-driscoll** [comment]
Once the builds pass we are ready to :shipit:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/omnisharp/omnisharp-atom/497)

**Comment by steelbrain** [comment]
AppVeyor seems to fail https://ci.appveyor.com/project/nosami/omnisharp-atom/build/933

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/omnisharp/omnisharp-atom/497)

**Comment by david-driscoll** [comment]
Appveyor... how I loath you sometimes.  Your changes wouldn't have caused the failure, so lets :shipit:.

I don't have permissions to restart the appveyor build @nosami could you add me onto your project in appveyor when you get a chance?

**Comment by david-driscoll** [comment]
Oh and thanks for the help @steelbrain !

**Comment by steelbrain** [comment]
The pleasure is all mine :bow:

**Pull request merged**
