### PR TITLE
"File -> New Project"

### PR DESCRIPTION
**Pull request by david-driscoll**
So we can't really do much to change the internals of the menu that atom hands off to the os.  Soooo I think this is a decent compromise.

The only menu item in `Packages -> OmniSharp` is now "New Application".  Then when OmniSharp is running a new top level menu is added after Help called "OmniSharp".  This has the build menu, rename, code format and other menu items in it.  When Omnisharp is turned off, the menu goes away.

### CODE REVIEW

**Comment by david-driscoll** [comment]
Will fix #114

**Comment by willl** [comment]
Interesting implementation with the menu being dynamically made available only when OmniSharp is toggled on, then disappearing when it's no longer available.

However, I also foresee some potential confusion if this feature isn't documented well. Especially without that auto-start when a recognised grammar is loaded. So my biggest issue with this implantation is that it's not going to be immediately obvious for new users. They will install the package, see that the menu shows "New Application" and not much else, and then they will wonder what is wrong with their install. Happy to be convinced otherwise.

**Comment by nosami** [comment]
The `New Project` menu is also visible via `Packages -> OmniSharp -> New Project`

**Comment by nosami** [comment]
`Package -> OmniSharp` should probably also have the `toggle` option. At least for now.

**Comment by david-driscoll** [comment]
Added the toggle back to the main menu.

@willl we can look at getting the auto toggle in fairly soon too, and then that should make it more obvious.

**Comment by willl** [comment]
:+1:  Cool :)

**Comment by david-driscoll** [comment]
see #160

**Comment by nosami** [comment]
I :heart: this PR

**Pull request merged**
