### PR TITLE
[WIP] OS dependent shortcut keys

### PR DESCRIPTION
**Pull request by ctolkien**
Don't merge.

Typescript help needed to make this less :hankey: . Currently method is copypasta'd to each view.

### CODE REVIEW

**Comment by ctolkien** [comment]
Ref #39

**Comment by ctolkien** [comment]
@willl suggested if we can get the keyboard combo from omnisharp-atom.cson keymap

**Comment by david-driscoll** [comment]
Looks good to me.

**Comment by willl** [comment]
:+1: Looks good to me too.

Just a note, I see that in the command palette code, they actually wrap `.keystrokes` in `humanizeKeystroke(bindings.keystrokes)`.

You can see that code in action here: https://github.com/atom/command-palette/blob/51028abeb1bbb072b82fc9aaa6ecd1123abcf0f3/lib/command-palette-view.coffee#L58

Which is defined here: https://github.com/atom/underscore-plus/blob/2046d1562896761e3c38b7a647ac30b87b46ea20/src/underscore-plus.coffee#L179

`# Humanize the keystroke according to platform conventions. This method
  # attempts to mirror the text the given keystroke would have if displayed in
  # a system menu.`

**Comment by ctolkien** [comment]
Will have a look to see if lodash has something similar.

**Comment by ctolkien** [comment]
Think we should kill this, project auto starts now?

**Comment by ctolkien** [comment]
No longer needed!

**Pull request closed without merging**
