### PR TITLE
Added typelookup tooltip to atom

### PR DESCRIPTION
**Pull request by david-driscoll**
based on atom-typescript

type-hover

### CODE REVIEW

**Comment by davidfowl** [comment]
Screen shot?

**Comment by david-driscoll** [comment]
That'd be good wouldn't it... god I must have been tired last night.
type-hover

**Comment by david-driscoll** [comment]
Now with better html encoding.

escaped-html

**Comment by willl** [comment]
Nice. Is it possible to add icons on the left like we have for intellisense?

Also, perhaps drop the font size a little?

**Comment by nosami** [comment]
Can't add the icon without changing the server side response. Nice idea though. Can we add that at a later date?

**Comment by nosami** [comment]
```
spacePen is not defined
Hide Stack Trace
ReferenceError: spacePen is not defined
    at Object.<anonymous> (/Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/tooltip-view.ts:47:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .ts] (/Users/jason/Downloads/Atom.app/Contents/Resources/app.asar/src/typescript.js:99:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/lookup.ts:5:19)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .ts] (/Users/jason/Downloads/Atom.app/Contents/Resources/app.asar/src/typescript.js:99:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at new Feature (/Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.ts:17:20)
    at /Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.ts:81:72
```

**Comment by nosami** [comment]
OK... This works fine after compiling the TS ;)

**Pull request merged**
