### PR TITLE
Project Json Intellisense

### PR DESCRIPTION
**Pull request by david-driscoll**

### CODE REVIEW

**Comment by Mpdreamz** [comment]
This will be awesome!

Tried it on `omnisharp-roslyn` but did not get any autocompletions for packages as expected.

**Comment by nosami** [comment]
@Mpdreamz it's _very_ slow, but it does work (did for me at least).

It needs some more work before it can be merged.

**Comment by david-driscoll** [comment]
Updated for latest client.

**Comment by david-driscoll** [comment]
The popup issue should be fixed in the next json schema provider.

**Comment by nosami** [comment]
Just tried it. It's working great now :)

**Comment by nosami** [comment]
This is in version v0.23.0

**Pull request merged**
