### PR TITLE
Config all the things

### PR DESCRIPTION
**Pull request by david-driscoll**
This branch is based from #480 (so it should go first).

This expands upon what we've been building for a while, with each feature broken up into it's own little box.  This will add the ability for a user to disable a feature they don't want/care about.  It is built into how we create features (as a mandatory part of the interface), so even new features will work this way.

Some features are required for omnisharp-atom to function correctly (these are things like the dock, solution information, server information, etc), so they won't be configurable.  It's entirely possible we'll add another mandatory field in the future.

### CODE REVIEW

**Comment by david-driscoll** [comment]
image

**Comment by nosami** [comment]
I'm not convinced that there is much point in having `Code format`, `Find Symbols`, `Find Usages` etc as config items.

If someone doesn't want to use them, they just won't use them :) Config should be for actions that are outside the users control.

**Comment by david-driscoll** [comment]
While I agree, I would have put Code Lens in the same bucket too.  I just
figure instead of creating one-off configs as needed, if we make something
generic, that "just works", if there is a new feature someone doesn't want,
we can just turn it off.

If we feel like something shouldn't be configurable (Code Format for
example), we can flip the flag that says the feature is required, and it
won't show up in the config at all.  So I'm open to flagging more features
as required.

**Comment by nosami** [comment]
OK. Anything that requires a keybinding to activate doesn't need a config item.

**Comment by david-driscoll** [comment]
Was using this all weekend, and didn't hit any snags that I know of, let me know if you have any issues pop up.

**Pull request merged**
