### PR TITLE
Migrate homegrown error system to use linter package

### PR DESCRIPTION
**Pull request by ctolkien**

### CODE REVIEW

**Comment by Mpdreamz** [comment]
My initial reservation was based on not being able to control the adornments. 

I have done a 180 on this with all the awesome work these guys have been on the atom-linter plugin recently and we need to play nice: if something is not supported we need to contribute back to `atom-linter`!

Again no bandwidth to test this sadly, although I might skip a session or two at dotnetfringe to get this in over the weekend. 

Another thing to note is that we might need to inspect is how to best merge both this as well the the typescript PR.

**Comment by Mpdreamz** [comment]
forgot required happy emoticons :+1: :clap: :tada: :birthday: ! :D In all seriousness I'm really happy with this!

**Comment by ctolkien** [comment]
my 2c re: moving forward - merge this and #93 in. Drop a new public release on APM. Then tackle the typescript PR (which ideally wouldn't have new features in it)

**Comment by Mpdreamz** [comment]
@ctolkien finally had time to check it out. 

I generally like the linter approach but have two opinions I like to run by you. 

The linter and autocomplete now really interfere with one another (having to popup windows). 

This PR removes the error output alltogether while that one is still useful to show errors across the whole solution. 

Is there something that we can do here?

Going to pull this in regardless since I do believe jumping on linter is the best thing to do here :+1: for the PR!

**Comment by ctolkien** [comment]
>The linter and autocomplete now really interfere with one another (having two popup windows).

Yeah I didn't observe this previously,  but deffo happening now. Might be with the newer versions of Autocomplete. Will take a look.

>This PR removes the error output alltogether while that one is still useful to show errors across the whole solution. 

Agreed, but there were a number of issues with it (if you removed all the issues from a file, it wouldn't actually update). I think we should chat with the guys running the linter package ( @park9140  ?) to see how we can move forward.

**Comment by park9140** [comment]
@ctolkien,  as for the autocomplete/linter interaction, currently the autocomplete attempts to overlay the linter window by setting it's z-index higher.  Checkout https://github.com/atom/atom/issues/4401, which is my attempt at starting a conversation about making overlays a little smarter when there are multiple on an editor.

For the multiple files thing.  I have been meaning to get back to adding support to linter for a v2 api that would support pushing errors to the linter rather than just pulling for them.  In this way you could send errors for files which you find in builds.  
Discussion of v2 api is below,
https://github.com/AtomLinter/Linter/issues/387

If you @reference me on any pull request you have for atom linter I can review and push it through if you want to take on any updates at all.

**Pull request merged**
