### PR TITLE
Codeactionsv2

### PR DESCRIPTION
**Pull request by nosami**

### CODE REVIEW

**Comment by nosami** [comment]
@david-driscoll seems to be mostly working except for 'Extract Method' which uses the selection.

**Comment by davidfowl** [comment]
:smile:

**Comment by david-driscoll** [comment]
I was able to get extract method to work.  I'll test some more today.

**Comment by nosami** [comment]
It sometimes works in a fashion.

It doesn't extract the region that you selected.

Also the lightbulb appears on the wrong line when you use a selection

**Comment by Mpdreamz** [comment]
LGTM :+1: seriously fucking awesome!

Tested all of these:

https://twitter.com/JasonImison/status/613560084799602688/photo/1
https://twitter.com/JasonImison/status/613560021608177664/photo/1
https://twitter.com/JasonImison/status/613559917480398848/photo/1

The only time I could not get `Extract Method` to work was when selecting lines in a constructor.

**Comment by nosami** [comment]
Extract method was broken on this branch - but worked fine on the old magic branch.

**Pull request merged**
