### PR TITLE
Open GoToDefinition directly on the correct line

### LINKED ISSUE #453: GoToDefinition opens files on line 1, and then navigates to the correct line
This is mostly a problem for jump-list style tracking of the cursor position - e.g. with the [cursor-history package](https://github.com/t9md/atom-cursor-history). I believe changing [omni.ts's NavigateTo](https://github.com/OmniSharp/omnisharp-atom/blob/e4da78720bb05a213d4b2c0740a76e9fcef0e2ad/lib/omni-sharp-server/omni.ts#L87) to use the response line and column fixes this.

### PR DESCRIPTION
**Pull request by tmunro**
This fixes #453. `navigateTo` should now open directly to the line and column of the response.

### CODE REVIEW

**Comment by nosami** [comment]
Looks like a nice change but should probably be rebased into one commit. I can do it if you want?

**Comment by nosami** [comment]
I just merged your last commit in here https://github.com/OmniSharp/omnisharp-atom/commit/1882b39d7aef4a2aca8cb1877008a54b6f9ec0e1 . This fix is in v0.22.6.

Thanks!

**Comment by tmunro** [comment]
Thanks, I should have done that rebase initially. Still getting the hang of some Git stuff :)

**Comment by nosami** [comment]
no worries :)

**Comment by david-driscoll** [comment]
:+1: Awesome.

-----Original Message-----

**Pull request closed without merging**
