### PR TITLE
Got unit tests working again...

### PR DESCRIPTION
**Pull request by david-driscoll**
Only a few tests now, but this should probably go in sooner rather than later.  I'll be working on some more tests after this.

### CODE REVIEW

**Comment by david-driscoll** [comment]
@mat-mcloughlin @Mpdreamz @nosami Anyone got any input / want to test this before we merge it in?

**Comment by nosami** [comment]
I'm not using Atom and don't have time to test it any more, sorry :(

**Comment by mat-mcloughlin** [comment]
I'll take a look at it

**Comment by david-driscoll** [comment]
@mat-mcloughlin Pretty simple, just run `apm test` from the console, or run specs from the command palette.

Tests run on travis now too, I just want to make sure nothing is broken to badly before shipping it :)

**Comment by willl** [comment]
@david-driscoll If you're ready for it, you can uncomment line 13 in the appveyor config file to enable tests on appveyor too. https://github.com/OmniSharp/omnisharp-atom/blob/master/appveyor.yml#L13

**Comment by david-driscoll** [comment]
Unfortunately at the moment chocolatey does not install the latest version of atom, so the tests fail because the version that gets installed is like 0.178

-----Original Message-----

**Comment by willl** [comment]
Haven't checked it for awhile, but I copied the original from here: https://github.com/atom/ci/blob/master/appveyor.yml

**Comment by david-driscoll** [comment]
@willl aye, for the time being I've disabled appveyor for testing.  Travis seems to be doing a really good job for us though.

**Comment by david-driscoll** [comment]
Appveyor works, thanks to a nice find from @willl !

**Comment by willl** [comment]
That's awesome @david-driscoll!

**Pull request merged**
