### PR TITLE
Inline code actions

### LINKED ISSUE #388: Code Fix completions should appear next to the text where you invoke the command.
Like this

from atom-typescript. We should totally copy it :)

### PR DESCRIPTION
**Pull request by nosami**
screen shot 2015-06-26 at 00 04 37

fixed #388

### CODE REVIEW

**Comment by Mpdreamz** [comment]
yes yes! reviewing now :+1:

**Comment by Mpdreamz** [comment]
alt+enter no longer pops up the codeactions 

`Uncaught TypeError: Cannot read property 'call' of undefined`

```
/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:579
Hide Stack Trace
TypeError: Cannot read property 'call' of undefined
  at CodeActionsView.setItems (/Users/mpdreamz/Projects/omnisharp-atom/lib/omnisharp-atom/views/code-actions-view.js:39:24)
  at Object.default_1 [as default] (/Users/mpdreamz/Projects/omnisharp-atom/lib/omnisharp-atom/views/code-actions-view.js:15:20)
  at AnonymousObserver._onNext (/Users/mpdreamz/Projects/omnisharp-atom/lib/omnisharp-atom/features/code-action.js:20:64)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1962:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1894:35)
  at AnonymousObserver.tryCatcher (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1894:35)
  at Subject.Rx.Subject.addProperties.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:5138:19)
  at Subject.tryCatcher (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1894:35)
  at AutoDetachObserver.tryCatcher (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1894:35)
  at InnerObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:3552:90)
  at InnerObserver.tryCatcher (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1894:35)
  at MapObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:4595:19)
  at MapObserver.tryCatcher (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1894:35)
  at AnonymousObserver._onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.aggregates.js:591:11)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1962:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1894:35)
  at AnonymousObserver.tryCatcher (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1894:35)
  at FilterObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:4899:34)
  at Subject.Rx.Subject.addProperties.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:5138:19)
  at AnonymousObserver._onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/omnisharp-client/lib/clients/client-base.js:204:35)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1962:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1894:35)
  at AnonymousObserver.tryCatcher (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1894:35)
  at AnonymousObserver._onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.time.js:602:20)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1962:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:1894:35)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/rx/dist/rx.js:5228:17)
  at StdioDriver.handlePacketResponse (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:189:22)
  at StdioDriver.handlePacket (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:173:18)
  at StdioDriver.handleData (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:167:18)
  at Interface.<anonymous> (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:115:54)
  at emitOne (events.js:77:13)
  at Interface.emit (events.js:166:7)
  at Interface._onLine (readline.js:195:10)
  at Interface.<anonymous> (readline.js:325:12)
  at Array.forEach (native)
  at Interface._normalWrite (readline.js:324:11)
  at Socket.ondata (readline.js:71:10)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)
```

**Comment by nosami** [comment]
eurgh... chad saw this error too.

I had it at one point also but couldn't understand what was going on. It failed on this line https://github.com/OmniSharp/omnisharp-atom/blob/inline-code-actions/lib/omnisharp-atom/views/code-actions-view.ts#L38 which makes no sense at all to me. Seems like some sort of typescript bug.

It went away for me but I have no idea why. :( Maybe @david-driscoll can help

**Comment by nosami** [comment]
Just looked at this again.. If I run `npm install` the problem is there... but if I generate js using atom-typescript, the problem goes away.

Seems that atom-typescript is on a different version

**Comment by david-driscoll** [comment]
:sparkles: :shipit:

**Pull request merged**
