### PR TITLE
CoffeeScript to TypeScript

### PR DESCRIPTION
**Pull request by david-driscoll**

### CODE REVIEW

**Comment by Mpdreamz** [comment]
:+1: :clap: :tada: :birthday: :gift: and a shitton of other emoticons!

Awesome work @david-driscoll !

This week and next week I do not have the bandwidth to give this PR the love it deserves but suffice to say this is f'ing awesome! :smile: 

@ctolkien @stephen-james you have time to review this? 

@david-driscoll we invited you to the atom-contributors group so you have direct push access to this repos, look in your email. The only rule we have though is to never pull your own PR's :)

**Comment by ctolkien** [comment]
Hooolllyy crap this has progressed a lot since the first commit! I'm slammed at work as well at the moment (and stricken with man-flu) but will see when I can give it a spin...

:clap:

**Comment by david-driscoll** [comment]
I figure this will take a little bit to bake.  I'll try to watch for any other changes and keep the branch updated with any other fixes.

**Comment by ctolkien** [comment]
@david-driscoll  - if you have a chance, can you look at migrating the (recently merged) linter.coffee - https://github.com/OmniSharp/omnisharp-atom/blob/master/lib/omnisharp-atom/linter.coffee

Then we can hopefully draw a line in the sand to get this in.

**Comment by david-driscoll** [comment]
I'll look at merging it in and updating anything new too.

I'm currently just trying to finish getting the atom typescript definitions up to date... it's helping solve some of the last few deprecations as well.

**Comment by willl** [comment]
Unless anyone can find other reasons, I propose we look at getting this merged.

Thing is, we don't have to have everything in typescript or coffeescript. We can mix and match both together in our package.

**Comment by ctolkien** [comment]
Yah the earlier we get this in, the better (stop people doing work in 2 langs). I've a PR outstanding on @david-driscoll 's repo which should bring things more or less up to date with master.

**Comment by willl** [comment]
As per the conversation on jabbr with @ctolkien, so let's keep a record of this...

1. Let's release a new copy of omnisharp-atom (so people who are relying on that have a new version) as is prior to merging.
2. Merge this PR.

Keep in mind that 0.2.1 uses omnisharp-server, while the current master (and potential 0.2.2) has switched over to omnisharp-roslyn. We'll also need to update the various build script that attempts to build omnisharp-server.

**Comment by ctolkien** [comment]
ping @Mpdreamz  for your input here.

**Comment by davidfowl** [comment]
OMNISHARP ROSLYN!!! :small_blue_diamond:

**Comment by sgwill** [comment]
Agreed. I'd love to get a release out soon, so TS can get merged and we can get back to adding features. It'd be nice to both be on Roslyn and have TS completed.

**Comment by david-driscoll** [comment]
@ctolkien updated!

**Comment by ctolkien** [comment]
hold on to your butts

**Pull request merged**
