### PR TITLE
Intellisense keys (make '.' work)

### PR DESCRIPTION
**Pull request by nosami**
This PR makes the '.' key work like it does in VS. 

intellisense-dot

It also closes the popup on space key.

### CODE REVIEW

**Comment by danbarua** [comment]
+1

**Comment by Yantrio** [comment]
Looking "crisp" :) I Like it :+1:

**Comment by Mpdreamz** [comment]
Awesome didn't know i was missing it until I tried it :+1: 
Small nag entering space to autocomplete will still insert a space

**Comment by nosami** [comment]
Shouldn't it enter a space? It's that long since I used VS that I don't remember! I did added the space on purpose.

**Comment by Mpdreamz** [comment]
Just verified against VS :+1:

**Comment by sgwill** [comment]
SO MUCH AWESOME

**Pull request merged**
