### PR TITLE
Configuration and build script for Travis CI

### PR DESCRIPTION
**Pull request by willl**

### CODE REVIEW

**Comment by willl** [comment]
Apparently to enable this, it needs someone who has admin rights to the repo (not just right access), to enable it at travis-ci.org.

**Comment by Mpdreamz** [comment]
Merging this in and then enabling it at travis-ci #yolo :+1:

**Comment by Mpdreamz** [comment]
Thanks for this @willl :)

will see how it plays out at:

https://travis-ci.org/OmniSharp/omnisharp-atom/builds

:pray:

**Comment by willl** [comment]
Looks like the build is failing when running the specs.

**Pull request merged**
