### PR TITLE
Perf/status bar

### PR DESCRIPTION
**Pull request by david-driscoll**
Alright... so I've made a few changes... I didn't really move the cheese at all, just made some of the client api's a little better.

## Internal Api Changes
* `makeRequest` and `makeDataRequest` are now gone.
  * Replaced is a method that manages the buffer based on the editor the client is sending a request for.
  * If you need to send an empty `FileName` or `Buffer` you can still do so by explicting setting those values to null on the request object.
  * This is all done before validation kicks off for a request, so you shouldn't see any `FileName must not be null` errors.
* new method `client.whenConnected()` on each solution object.
  * this method allows you to defer making a request until the solution is connected, if the solution is already connected then it will trigger immediately.
* new method `Omni.whenEditorConnected(editor)`
  * Uses the new `whenConnected()` method, but uses the editor to find the solution to check against.
* new observable `Omni.activeEditorOrConfigEditor`
  * Publishes for active editors or config editors (project.json files), publishes null when the active editor is not one of those.
* new method `Omni.switchActiveEditor((editor, cd) => void)`
  * Not a new method, but good to know about.  When the active editor switches, the composite disposable `cd` is disposed, then the next editor is passed into the callback.
  * This is useful for features that have some weight to them, that only need to be active for the editor the user is currently using.
* new method `Omni.eachEditor((editor, cd) => void)`
* new method `Omni.eachConfigEditor((editor, cd) => void)`
  * When a new editor is added this method is invoked.
  * When an editor is disposed, the composite disposable `cd` is disposed automatically.

## Code Check
* Added new `omnisharp-atom:code-check` command to force a full diagnostics check
* Added a refresh button, that triggers the code-check command.
* By default any other code checks will only run against the one file.

## Rebuilt OmniSharp Status Bar
I determined that a large part of why we're seeing such slow usage in the UI is layout thrashing, around the status bar in the UI.

This was due one part to React
* In this case for the status bar React was like using a fork lift to move a sack of potatoes.

Another part with to many updates getting sent to the status bar
  * These have been toned down in the client (and are configurable if needed).

I have rebuilt the entire set of controls as standard Web Components, and while the code is _*way way*_ more verbose, I'm also noticing significant gains in performance when just coding away.

We may want to address rewriting the Dock and everything else as web components as well, but when the are closed, React is doing next to nothing.  The do have some impact while open, but not nearly on the same level as the Status Bar had (since the status bar is updated regularly and the typical dock window is not)

### CODE REVIEW

**Comment by david-driscoll** [comment]
cc @OmniSharp/atom-contributors 
If anyone has a chance to look this one over, it's no trivial so I don't want to merge it until we've had some extra testing against it.

**Comment by Mpdreamz** [comment]
Gonna have a pass at it today! Lot to take in :+1:

**Comment by mat-mcloughlin** [comment]
I got some time this afternoon so I'll take a look then

**Comment by Mpdreamz** [comment]
This looks and feels much better (might just be a placebo but meh who cares!)

Getting the following trying to toggle code lense on:

```
/findusages: 404 461ms
/findusages: 404 667ms
An unhandled exception has occurred: Object reference not set to an instance of an object
System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.CodeAnalysis.FindSymbols.Finders.LinkedFileReferenceFinder+d__0.MoveNext () [0x00000] in :0 
```

Seems to be related too:

```
TypeError: Cannot read property 'dispose' of undefined
  at React.DOM.a.onMouseLeave (/Users/mpdreamz/Projects/omnisharp-atom/lib/omnisharp-atom/atom/feature-buttons.js:141:34)
  at executeDispatch (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/react/lib/EventPluginUtils.js:110:21)
  at forEachEventDispatch (/Users/mpdreamz/Projects/omnisharp-atom/node_modules/react/lib/EventPluginUtils.js:98:5)
```

I'm not personally a fan of the feature toggle buttons cluttering the statusbar. 

Maybe move the refresh button to the project overview mini pane next to restart? At first  glance it feels out of place/nondescript 

Other then that its looking good!

**Comment by david-driscoll** [comment]
I'm running into the same code lens issue... but I can't figure out why it's throwing... it's just something inside roslyn that's getting angry so far as I can tell.

For the status bar buttons, they can be toggled off (I figured that would be a personal preference)
image

**Comment by Mpdreamz** [comment]
Well I like them on the omnisharp panel, just not on the status bar :)

**Comment by david-driscoll** [comment]
They're split into two different features, one for the editor, and one for the omnisharp panel! :smile:

**Comment by david-driscoll** [comment]
image

**Comment by david-driscoll** [comment]
I think I'll rename it from `Feature Editor Buttons` to `Feature Status Bar Buttons` to better explain what it's going to disable/enable.

**Comment by david-driscoll** [comment]
Long running branches suck!

I've been dog fooding this for the entire process of working on https://github.com/OmniSharp/omnisharp-roslyn/pull/293, so far I've only encountered edge case issues with highlighting (which the fundamentals have not changed).

If anyone else can give some input over the next day or two, we should get this merged and released!

**Comment by Mpdreamz** [comment]
Other then the codelens issue this branch had my +1 will try the updates tonight

**Comment by david-driscoll** [comment]
Thanks @Mpdreamz @mat-mcloughlin ... I was clearly delusional because I thought the error was also happening on master (it was not!).

That is is now.

**Comment by mat-mcloughlin** [comment]
Been using this branch for a while now. I'm not suffering any problems and it certainly feels a lot snappier

**Pull request merged**
