### PR TITLE
Sgwill toggle off

### PR DESCRIPTION
**Pull request by nosami**
Fixing whitespace issues from https://github.com/OmniSharp/omnisharp-atom/pull/153

### CODE REVIEW

**Comment by sgwill** [comment]
Great !

**Comment by sgwill** [comment]
Yikes, I hadn't looked at the diff here. I'm not sure which of my machines has the wrong spacing or line ending config. I'll check that out.

**Comment by nosami** [comment]
Always good to check the diff on github after creating a PR :)

**Comment by sgwill** [comment]
Yes, I usually do. I didn't after one of the merge-fixes. Lesson learned.

**Pull request merged**
