### PR TITLE
WIP: Linter V2

### PR DESCRIPTION
**Pull request by ctolkien**
Don't merge, etc.

- [ ] Single file (on the fly) linter
- [ ] Project wide linter
- [ ] Styling for info messages
- [ ] bring CSX support back
- [ ] Keybindings and other nice to haves
- [ ] @david-driscoll to fix all my TS/RX
- [ ] Traces support - Don't think this applies for us.

Ref: https://github.com/OmniSharp/omnisharp-atom/issues/364

### CODE REVIEW

**Comment by david-driscoll** [comment]
@ctolkien I've rebased and made some changes, let me know if you have a chance to test it, see if it works for you.

**Comment by ctolkien** [comment]
Cheers. FYI I'm away at the moment, will be back in a few days.

________________________________

**Comment by willl** [comment]
Starting to get deprecation warnings with regards to the linter now.

AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
Object.activate (C:\Users\william\.atom\packages\linter\lib\main.coffee:57:8)
Package.activateNow (C:\Users\william\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:240:19)
<unknown> (C:\Users\william\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:221:30)
Package.measure (C:\Users\william\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:165:15)
Package.activate (C:\Users\william\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:213:14)
PackageManager.activatePackage (C:\Users\william\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package-manager.js:452:21)
```

**Comment by ctolkien** [comment]
Hrmm crap re: deprecation warnings. Real life :tm:  is consistently getting in the way :/. 

Has anyone had a chance to take a look at how this is shaped up at the moment? I believe things should be in a pretty good state after @david-driscoll fixed all my code :heart_eyes:

**Comment by david-driscoll** [comment]
If someone wants to test the PR, I pushed all the fixes to the same branch.

**Comment by david-driscoll** [comment]
Merging, we can address @nosami `paths` issue tomorrow it looks unrelated when I look at the source that's changing.

**Pull request merged**
