### PR TITLE
Locally Cached auto complete

### PR DESCRIPTION
**Pull request by david-driscoll**
This depends on the node-client, hence the hugh list of commits >.<

But it works and seems much snappier.

### CODE REVIEW

**Comment by davidfowl** [comment]
When do you bust the cache? What does it cache on?

**Comment by david-driscoll** [comment]
It breaks if the cursor jumps up or down, moves greater than 5 characters away from the it's current position (we could probably bring that down to 2, and still be good).  It also breaks on `.`

https://github.com/OmniSharp/omnisharp-atom/pull/197/files#diff-e4b51561ac170591746f717206f29e81R51

**Comment by nosami** [comment]
It needs to clear the cache when deleting a `.` too

**Comment by nosami** [comment]
The fuzzy matching is working against the wrong field. See screenshot 
screen shot 2015-05-03 at 22 25 41 We shouldn't be matching against method params :)

**Comment by nosami** [comment]
Overall though, it seems to make intellisense quite a lot smoother for me. Will be awesome when those issues are fixed :+1:

**Comment by nosami** [comment]
Just noticed that I can't complete a using statement namespace.

**Comment by nosami** [comment]
This seems to be working as far as I can tell now except for the completing namespaces with `using` bug.

using-bug

**Comment by nosami** [comment]
Using bug is fixed... but I found another 
using-bug2

**Comment by nosami** [comment]
merged

**Pull request closed without merging**
