### PR TITLE
Feature/feature toggle buttons

### PR DESCRIPTION
**Pull request by david-driscoll**
Quick little feature that adds buttons linked to the highlighting setting and code lens setting, so that's it's easy to toggle, these sometimes heavy features.

image

I do note some issues with code-lens not disppearing like they should, this is existing anyway, so I'll look at that in my fixes branch which I was working on over the weekend.

### CODE REVIEW

**Comment by Mpdreamz** [comment]
The settings button does not work for me :(

The buttons could use a tooltip indicating what clicking the button will do e.g

"Clicking this button will disable/enable highlighting"

**Comment by david-driscoll** [comment]
@Mpdreamz whats it do?  Just nothing?  Or does it open the atom settings window?

**Comment by Mpdreamz** [comment]
Nothing, nothing bad happens in console either.

**Comment by david-driscoll** [comment]
I had forgotten a `t` in `settings` :imp: 

Should be good to go... along with this easy to toggle features... I made it easier for those that like the command palette to enable / disable features.

**Pull request merged**
