### PR TITLE
Feature/test runner

### PR DESCRIPTION
**Pull request by mat-mcloughlin**
This isn't quiet ready yet but I've got a couple of questions so I thought I'd create a PR

- Should we pass through buffer when running the tests. Was a little confusing when I hadn't saved my file. I'd say probably not but just highlighting it.

- Atom doesn't allow for "chained" shortcuts so I can't do the usual `cmd + u, cmd + t` so any ideas what to use for the defaults?

### CODE REVIEW

**Comment by nosami** [comment]
First time I ever used bullet points in a comment - it's faster than typing full sentences ;)

- Yes, you should pass the buffer through
- Need to save files before running tests too.
- Atom does allow chained shortcuts
- Ctrl-R, Ctrl-T etc - RT, RF, RA, RL
- Readme
- Context menus

**Comment by mat-mcloughlin** [comment]
- ok
- ok
- sure? I tried but will look further
- ok
- will do
- shit I forgot

:)

**Comment by nosami** [comment]
Look at the existing keybinds. We use ctrl-k, ctrl-d to reformat etc

**Comment by mat-mcloughlin** [comment]
so it does... thanks!

**Comment by ctolkien** [comment]
:+1:

**Comment by david-driscoll** [comment]
:shipit:

**Pull request merged**
